name: Publish

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Compile and Deploy
        uses: jonhue/pubtex-action@main
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          pre_compile_command:
          files: |
            logique-notes.tex
